export const GET_COMMENTS = "GET_COMMENTS";
export const GET_COMMENTS_REQUESTED = "GET_COMMENTS_REQUESTED";
export const SET_CURRENT_COMMENT = "SET_CURRENT_COMMENT";
export const WRITE_COMMENT_RESULT = "WRITE_COMMENT_RESULT";
export const WRITE_COMMENT_REQUESTED = "WRITE_COMMENT_REQUESTED";
export const CLEAR_TEXTAREA = "CLEAR_TEXTAREA";
export const GET_CURRENT_COMMENT_ID = "GET_CURRENT_COMMENT_ID";
