export const GET_CURRENT_PAGE = 'GET_CURRENT_PAGE';
export const GET_POSTS = 'GET_POSTS';
export const GET_POSTS_REQUSETED = 'GET_POSTS_REQUSETED';
export const GET_POST = 'GET_POST';
export const GET_POST_REQUSETED = 'GET_POST_REQUSETED';
export const GET_CURRENT_POST_ID = 'GET_CURRENT_POST_ID';
