export const SET_LOADING = "SET_LOADING";
export const GET_CONTENT = "GET_CONTENT";
export const GET_PREVIEW = "GET_PREVIEW";
export const GET_RESULT = "GET_RESULT";
export const GET_RESULT_REQUESTED = "GET_RESULT_REQUESTED";
